<?xml version="1.0" encoding="UTF-8"?>
<!-- SPDX-License-Identifier: EPL-2.0 -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>org.eclipse.kura</groupId><artifactId>kura-cloud</artifactId><version>3.0.0-SNAPSHOT</version><relativePath>../pom.xml</relativePath></parent>
  <artifactId>kura-cloud-runtime-tests</artifactId>
  <dependencies>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>kura-test-support</artifactId><version>6.0.0-SNAPSHOT</version><scope>test</scope></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.useradmin.store</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>com.google.code.gson</groupId><artifactId>gson</artifactId><version>2.11.0</version><scope>test</scope></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.request.handler.jaxrs</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.rest.configuration.provider</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.rest.cloudconnection.provider</artifactId><version>3.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider</artifactId><version>3.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>com.github.moquette-io.moquette</groupId><artifactId>moquette-broker</artifactId><version>0.18.0</version><scope>test</scope>
      <exclusions><exclusion><groupId>org.slf4j</groupId><artifactId>slf4j-reload4j</artifactId></exclusion><exclusion><groupId>com.h2database</groupId><artifactId>h2-mvstore</artifactId></exclusion></exclusions>
    </dependency>
    <dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><version>2.3.232</version><scope>test</scope></dependency>
    <dependency><groupId>org.eclipse.paho</groupId><artifactId>org.eclipse.paho.client.mqttv3</artifactId><version>1.2.5</version><scope>test</scope></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>kura-osgi-test-support</artifactId><version>6.0.0-SNAPSHOT</version><scope>test</scope></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.api</artifactId><version>3.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.cloud.base.provider</artifactId><version>3.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.cloudconnection.kapua.mqtt.provider</artifactId><version>3.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.cloud.factory</artifactId><version>3.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.configuration</artifactId><version>3.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.crypto</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.inventory</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.keystore</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.db.h2db.provider</artifactId><version>1.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.json.marshaller.unmarshaller.provider</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.util</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
    <dependency><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.xml.marshaller.unmarshaller.provider</artifactId><version>2.0.0-SNAPSHOT</version><type>pom</type><scope>test</scope><exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions></dependency>
  </dependencies>
  <repositories><repository><id>jitpack.io</id><url>https://jitpack.io</url></repository></repositories>
  <build><plugins>
    <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-dependency-plugin</artifactId>
      <executions><execution><id>prepare-real-cloud-bundles</id><phase>process-test-resources</phase><goals><goal>copy</goal></goals>
        <configuration><outputDirectory>${project.build.directory}/it-bundles</outputDirectory><overWriteSnapshots>true</overWriteSnapshots><artifactItems>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.useradmin.store</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.useradmin.store.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.felix</groupId><artifactId>org.apache.felix.useradmin</artifactId><version>1.0.4</version><destFileName>org.apache.felix.useradmin.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.glassfish.hk2</groupId><artifactId>osgi-resource-locator</artifactId><version>1.0.3</version><destFileName>osgi-resource-locator.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.glassfish.jersey.core</groupId><artifactId>jersey-common</artifactId><version>3.1.9</version><destFileName>jersey-common.jar</destFileName></artifactItem>
          <artifactItem><groupId>jakarta.inject</groupId><artifactId>jakarta.inject-api</artifactId><version>2.0.1</version><destFileName>jakarta.inject-api.jar</destFileName></artifactItem>
          <artifactItem><groupId>jakarta.annotation</groupId><artifactId>jakarta.annotation-api</artifactId><version>2.1.1</version><destFileName>jakarta.annotation-api.jar</destFileName></artifactItem>
          <artifactItem><groupId>jakarta.ws.rs</groupId><artifactId>jakarta.ws.rs-api</artifactId><version>3.1.0</version><destFileName>jakarta.ws.rs-api.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.request.handler.jaxrs</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.request.handler.jaxrs.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.rest.configuration.provider</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.rest.configuration.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.rest.cloudconnection.provider</artifactId><version>3.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.rest.cloudconnection.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider</artifactId><version>3.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.bouncycastle</groupId><artifactId>bcpkix-jdk18on</artifactId><version>1.86</version><destFileName>bcpkix.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.bouncycastle</groupId><artifactId>bcprov-jdk18on</artifactId><version>1.86</version><destFileName>bcprov.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.bouncycastle</groupId><artifactId>bcutil-jdk18on</artifactId><version>1.86</version><destFileName>bcutil.jar</destFileName></artifactItem>
          <artifactItem><groupId>com.google.code.gson</groupId><artifactId>gson</artifactId><version>2.11.0</version><destFileName>com.google.gson.jar</destFileName></artifactItem>
          <artifactItem><groupId>com.google.guava</groupId><artifactId>guava</artifactId><version>33.4.0-jre</version><destFileName>com.google.guava.jar</destFileName></artifactItem>
          <artifactItem><groupId>com.google.guava</groupId><artifactId>failureaccess</artifactId><version>1.0.2</version><destFileName>com.google.guava.failureaccess.jar</destFileName></artifactItem>
          <artifactItem><groupId>com.google.protobuf</groupId><artifactId>protobuf-java</artifactId><version>4.30.2</version><destFileName>com.google.protobuf.jar</destFileName></artifactItem>
          <artifactItem><groupId>com.h2database</groupId><artifactId>h2</artifactId><version>2.3.232</version><destFileName>com.h2database.jar</destFileName></artifactItem>
          <artifactItem><groupId>com.eclipsesource.minimal-json</groupId><artifactId>minimal-json</artifactId><version>0.9.5</version><destFileName>minimal-json.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.aries.spifly</groupId><artifactId>org.apache.aries.spifly.dynamic.bundle</artifactId><version>1.3.7</version><destFileName>org.apache.aries.spifly.dynamic.bundle.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.commons</groupId><artifactId>commons-exec</artifactId><version>1.4.0</version><destFileName>org.apache.commons.commons-exec.jar</destFileName></artifactItem>
          <artifactItem><groupId>commons-io</groupId><artifactId>commons-io</artifactId><version>2.21.0</version><destFileName>org.apache.commons.commons-io.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.felix</groupId><artifactId>org.apache.felix.dependencymanager</artifactId><version>4.6.1</version><destFileName>org.apache.felix.dependencymanager.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.felix</groupId><artifactId>org.apache.felix.deploymentadmin</artifactId><version>0.9.10</version><destFileName>org.apache.felix.deploymentadmin.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.felix</groupId><artifactId>org.apache.felix.scr</artifactId><version>2.2.14</version><destFileName>org.apache.felix.scr.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-api</artifactId><version>2.26.0</version><destFileName>org.apache.logging.log4j.api.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-core</artifactId><version>2.26.0</version><destFileName>org.apache.logging.log4j.core.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-slf4j2-impl</artifactId><version>2.26.0</version><destFileName>org.apache.logging.log4j.slf4j2.impl.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.platform</groupId><artifactId>org.eclipse.equinox.cm</artifactId><version>1.6.400</version><destFileName>org.eclipse.equinox.cm.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.platform</groupId><artifactId>org.eclipse.equinox.event</artifactId><version>1.7.300</version><destFileName>org.eclipse.equinox.event.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.platform</groupId><artifactId>org.eclipse.equinox.metatype</artifactId><version>1.6.900</version><destFileName>org.eclipse.equinox.metatype.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.api</artifactId><version>3.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.api.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.cloud.base.provider</artifactId><version>3.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.cloud.base.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.cloudconnection.kapua.mqtt.provider</artifactId><version>3.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.cloudconnection.kapua.mqtt.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.core.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.cloud.factory</artifactId><version>3.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.core.cloud.factory.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.configuration</artifactId><version>3.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.core.configuration.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.crypto</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.core.crypto.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.inventory</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.core.inventory.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.core.keystore</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.core.keystore.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.db.h2db.provider</artifactId><version>1.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.db.h2db.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.json.marshaller.unmarshaller.provider</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.json.marshaller.unmarshaller.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.util</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.util.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.kura</groupId><artifactId>org.eclipse.kura.xml.marshaller.unmarshaller.provider</artifactId><version>2.0.0-SNAPSHOT</version><destFileName>org.eclipse.kura.xml.marshaller.unmarshaller.provider.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.eclipse.paho</groupId><artifactId>org.eclipse.paho.client.mqttv3</artifactId><version>1.2.5</version><destFileName>org.eclipse.paho.client.mqttv3.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.ow2.asm</groupId><artifactId>asm</artifactId><version>9.7.1</version><destFileName>org.objectweb.asm.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.ow2.asm</groupId><artifactId>asm-commons</artifactId><version>9.7.1</version><destFileName>org.objectweb.asm.commons.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.ow2.asm</groupId><artifactId>asm-tree</artifactId><version>9.7.1</version><destFileName>org.objectweb.asm.tree.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.ow2.asm</groupId><artifactId>asm-analysis</artifactId><version>9.7.1</version><destFileName>org.objectweb.asm.tree.analysis.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.ow2.asm</groupId><artifactId>asm-util</artifactId><version>9.7.1</version><destFileName>org.objectweb.asm.util.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.service.cm</artifactId><version>1.6.1</version><destFileName>org.osgi.service.cm.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.service.component</artifactId><version>1.5.1</version><destFileName>org.osgi.service.component.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.service.coordinator</artifactId><version>1.0.2</version><destFileName>org.osgi.service.coordinator.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.service.event</artifactId><version>1.4.1</version><destFileName>org.osgi.service.event.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.service.metatype</artifactId><version>1.4.1</version><destFileName>org.osgi.service.metatype.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.service.wireadmin</artifactId><version>1.0.2</version><destFileName>org.osgi.service.wireadmin.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.util.function</artifactId><version>1.2.0</version><destFileName>org.osgi.util.function.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.util.measurement</artifactId><version>1.0.2</version><destFileName>org.osgi.util.measurement.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.util.position</artifactId><version>1.0.1</version><destFileName>org.osgi.util.position.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.util.promise</artifactId><version>1.3.0</version><destFileName>org.osgi.util.promise.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.quartz-scheduler</groupId><artifactId>quartz</artifactId><version>2.5.0</version><destFileName>quartz.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId><version>2.0.18</version><destFileName>slf4j.api.jar</destFileName></artifactItem>
          <artifactItem><groupId>org.osgi</groupId><artifactId>org.osgi.service.useradmin</artifactId><version>1.1.1</version><destFileName>org.osgi.service.useradmin.jar</destFileName></artifactItem>
        </artifactItems></configuration>
      </execution></executions>
    </plugin>
    <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-failsafe-plugin</artifactId>
      <executions><execution><goals><goal>integration-test</goal><goal>verify</goal></goals></execution></executions>
    </plugin>
  </plugins></build>
</project>
